### PR TITLE
[WIP] spli the client from cli (take 2.1)

### PR DESCRIPTION
**Pull request by Fak3**

### CODE REVIEW

**Comment by rufuspollock** [comment]
General comment: Please give more descriptive PR items e.g.  this could have been:

```
Client validate tests.
```

In terms of commit message:

```
[client][m]: add tests for client.validate() [and anything else you did]
```

**Comment by rufuspollock** [comment]
Overall looks very good. Merging now.

**Comment by Fak3** [comment]
In the commit message - what does the items inside brackets mean?

**Comment by rufuspollock** [comment]
@Fak3 did you read @anuveyatsu gist about this? If not, ask him.

**Pull request merged**
